"""Validate the analytical Blackjack MDP against Gymnasium.

Three checks, in order of strictness:

1. **Probability sanity.** For every (state, action), transition probabilities
   sum to 1. For every dealer first-card, the dealer playout distribution
   sums to 1. These are internal consistency checks; failure here means a
   typo in the code, not a modelling error.

2. **Dealer distribution spot-check.** Compare our analytical dealer
   distribution for a given visible card against many Gym dealer playouts
   generated by sticking immediately (so dealer always plays out). This
   catches bugs in dealer logic (ace handling, soft-17 rule, etc).

3. **VI value vs empirical return.** Solve VI on our MDP, roll the greedy
   policy through Gymnasium many times, and check the average return
   matches V*(initial_state) marginalised over Gym's initial distribution.
   This is the strongest end-to-end check: it would fail for *any* bug in
   either transitions() or the reward function.

Usage:
    python scripts/validate_blackjack.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import numpy as np  # noqa: E402

from src.agents.vi import ValueIteration  # noqa: E402
from src.envs.blackjack import Blackjack, _dealer_dist_from_first_card  # noqa: E402


def check_probability_sanity(env: Blackjack) -> list[str]:
    """Returns list of failure messages (empty if all good)."""
    fails = []
    for s in env.all_states():
        for a in range(env.N_ACTIONS):
            total = sum(p for p, _, _ in env.transitions(s, a))
            if abs(total - 1.0) > 1e-9:
                fails.append(f"state={s} action={a}: probs sum to {total:.6g}")

    for card in range(1, 11):
        dist = _dealer_dist_from_first_card(card)
        total = sum(dist.values())
        if abs(total - 1.0) > 1e-9:
            fails.append(f"dealer first_card={card}: dist sums to {total:.6g}")
    return fails


def check_dealer_distribution(n_trials: int = 100_000, card: int = 10) -> list[str]:
    """Empirically roll out dealer hands via Gym; compare to analytical dist.

    We force a stick policy from a state whose dealer shows `card`, and look
    at the Gym env's dealer hand after termination.
    """
    import gymnasium as gym

    env = gym.make("Blackjack-v1")

    analytical = _dealer_dist_from_first_card(card)

    counts: dict[int, int] = {}
    collected = 0
    rng = np.random.default_rng(0)
    attempts = 0
    while collected < n_trials and attempts < n_trials * 50:
        attempts += 1
        obs, _ = env.reset(seed=int(rng.integers(0, 2**31 - 1)))
        if obs[1] != card:
            continue
        # Stick immediately; dealer plays out
        env.step(0)
        dealer_hand = env.unwrapped.dealer
        final_sum = _gym_sum(dealer_hand)
        bucket = min(final_sum, 22)  # fold busts into sentinel 22
        counts[bucket] = counts.get(bucket, 0) + 1
        collected += 1

    if collected < n_trials:
        return [
            f"dealer check: only collected {collected}/{n_trials} samples "
            f"for card={card}"
        ]

    fails = []
    for sum_val in sorted(set(analytical) | set(counts)):
        emp = counts.get(sum_val, 0) / collected
        analytic = analytical.get(sum_val, 0.0)
        # 4 standard deviations ~ 99.99% confidence on a binomial
        sigma = max(np.sqrt(analytic * (1 - analytic) / collected), 1e-9)
        if abs(emp - analytic) > 4 * sigma:
            fails.append(
                f"dealer first_card={card}, final_sum={sum_val}: "
                f"analytical={analytic:.4f}  empirical={emp:.4f}  "
                f"(4-sigma = {4*sigma:.4f})"
            )
    return fails


def _gym_sum(hand: list[int]) -> int:
    """Replicate Gymnasium's sum_hand: ace = 11 if non-busting, else 1."""
    if 1 in hand and sum(hand) + 10 <= 21:
        return sum(hand) + 10
    return sum(hand)


def check_vi_value_vs_rollouts(n_rollouts: int = 50_000) -> list[str]:
    """End-to-end check: VI's V* should match empirical eval return.

    We solve the MDP, then for many Gymnasium rollouts:
    - record the initial state s0
    - run the greedy policy to termination
    - accumulate the realised return

    The empirical mean return should equal E_{s0 ~ init}[V*(s0)]
    within sampling error. Because we don't have Gym's exact initial
    distribution analytically, we estimate E[V*(s0)] from the observed
    initial states themselves, which is unbiased.
    """
    env = Blackjack(seed=0)
    vi = ValueIteration(theta=1e-10, max_sweeps=1000)
    result = vi.run(env, n_episodes=0, eval_episodes=0, gamma=1.0, seed=0)

    Q = result["Q"]
    policy = result["policy"]

    # Reconstruct V from Q and policy (equivalent under greedy).
    def V(s):
        if s == Blackjack.TERMINAL:
            return 0.0
        return Q[s][policy[s]]

    import gymnasium as gym
    gym_env = gym.make("Blackjack-v1")

    expected_under_vstar = 0.0
    empirical_return = 0.0
    rng = np.random.default_rng(42)
    for _ in range(n_rollouts):
        obs, _ = gym_env.reset(seed=int(rng.integers(0, 2**31 - 1)))
        s0 = (int(obs[0]), int(obs[1]), int(obs[2]))
        expected_under_vstar += V(s0)

        s = s0
        total = 0.0
        terminated = truncated = False
        while not (terminated or truncated):
            a = policy[s]
            obs, r, terminated, truncated, _ = gym_env.step(int(a))
            total += r
            if not (terminated or truncated):
                s = (int(obs[0]), int(obs[1]), int(obs[2]))
        empirical_return += total

    expected_under_vstar /= n_rollouts
    empirical_return /= n_rollouts

    # Both are empirical means of unit-variance-ish quantities over n_rollouts;
    # 4 sigma on the difference is ~ 4 * sqrt(2) / sqrt(n_rollouts).
    tol = 4 * np.sqrt(2) / np.sqrt(n_rollouts)
    diff = abs(expected_under_vstar - empirical_return)

    print(f"    expected under V*: {expected_under_vstar:+.4f}")
    print(f"    empirical return : {empirical_return:+.4f}")
    print(f"    |diff|={diff:.4f}   tol(4σ)={tol:.4f}")

    if diff > tol:
        return [
            f"VI mismatch: |V*_mean - empirical| = {diff:.4f} > tol={tol:.4f}"
        ]
    return []


def main() -> int:
    env = Blackjack(seed=0)

    print("=== Blackjack MDP validation ===\n")

    print("[1/3] probability sanity ...", flush=True)
    fails = check_probability_sanity(env)
    if fails:
        print("  FAIL")
        for f in fails[:10]:
            print(f"    {f}")
        return 1
    print("  OK")

    print("\n[2/3] dealer distribution (card=10, 100k trials) ...", flush=True)
    fails = check_dealer_distribution()
    if fails:
        print("  FAIL")
        for f in fails:
            print(f"    {f}")
        return 1
    print("  OK")

    print("\n[3/3] VI value vs Gymnasium rollouts (50k rollouts) ...", flush=True)
    fails = check_vi_value_vs_rollouts()
    if fails:
        print("  FAIL")
        for f in fails:
            print(f"    {f}")
        return 1
    print("  OK")

    print("\nAll Blackjack MDP checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
